version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./app.db
      - SECRET_KEY=your-secret-key-change-in-production
      - DEBUG=True
    volumes:
      - ./app:/app/app
    depends_on:
      - db
    # The service includes all application features: user management, authentication,
    # profile management, notifications, and private messaging between users
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: fastapi_db
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: